apiVersion: v1
kind: Namespace
metadata:
  name: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: {{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  linkAccess: route
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: ie-gateway-{{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: ie-gateway-{{ .Values.clusterName }}
  host: spoke-gateway-istio.spoke-gateway-system.svc.cluster.local
  port: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: prometheus-{{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: prometheus-{{ .Values.clusterName }}
  host: thanos-querier.openshift-monitoring.svc.cluster.local
  port: 9091
