apiVersion: v1
kind: Namespace
metadata:
  name: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable-2
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: {{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  linkAccess: route
---
apiVersion: skupper.io/v2alpha1
kind: Link
metadata:
  name: link-to-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  endpoints:
    - host: skupper-router-service-interconnect.{{ .Values.hubClusterDomain }}
      port: "443"
      name: inter-router
    - host: skupper-router-edge-service-interconnect.{{ .Values.hubClusterDomain }}
      port: "443"
      name: edge
  tlsCredentials: link-to-hub-tls
  cost: 1
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: ie-gateway-{{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: ie-gateway-{{ .Values.clusterName }}
  host: spoke-gateway-istio.spoke-gateway-system.svc.cluster.local
  port: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: prometheus-{{ .Values.clusterName }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: prometheus-{{ .Values.clusterName }}
  host: thanos-querier.openshift-monitoring.svc.cluster.local
  port: 9091
