apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
  namespace: openshift-opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      otlp:
        endpoint: "tempo-simplest-distributor.distributed-tracing.svc:4317"
        tls:
          insecure: true
        headers:
          x-scope-orgid: platform
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
