gitops:
  repoUrl: "https://github.com/maximilianoPizarro/platform-hub-spoke-config"
  revision: "east"
  basePath: "."

argocd:
  namespace: openshift-gitops
  project: default

clusters:
  hub:
    domain: "apps.cluster-xqg4c.dynamic2.redhatworkshops.io"
  east:
    domain: ""
  west:
    domain: ""

connectivityLink:
  operators:
    channel: stable-4.20
    version: 4.20.4
    subscriptions:
      - name: amq-broker-rhel8
        namespace: industrial-edge-tst-all
        channel: 7.12.x
        source: redhat-operators
      - name: camel-k
        namespace: openshift-operators
        channel: stable-v2
        source: community-operators
      - name: amq-streams
        namespace: openshift-operators
        channel: stable
        source: redhat-operators

  apps: []

deployer:
  domain: ""
  apiUrl: ""

fieldContent:
  deploymentType: "helm"
