registration:
  enabled: true
  maxUsers: 200
  adminToken: "workshop-admin-2024"

keycloak:
  url: ""
  realm: "backstage"
  adminUser: "admin"
  adminPassword: ""

showroom:
  url: ""

deployer:
  domain: ""

clusters:
  east:
    domain: ""
  west:
    domain: ""
