apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.name }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ${{ values.name }}
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 512Mi
            cpu: 1
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cirros
              password: Welcome123!
              chpasswd: { expire: false }
              ssh_pwauth: true
