apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: industrial-edge-spoke
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
    argocd.argoproj.io/application-set-controller: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: hub-spoke-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{`{{name}}-spoke-components`}}'
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{`{{name}}`}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
      labels:
        app.kubernetes.io/part-of: platform-hub-spoke
        apps.open-cluster-management.io/cluster-set: global
    spec:
      project: default
      source:
        repoURL: {{ .Values.gitops.repoUrl }}
        targetRevision: {{ .Values.gitops.revision | default "main" | quote }}
        path: components/spoke-components
        helm:
          valuesObject:
            clusterName: '{{`{{name}}`}}'
            clusterDomain: '{{`{{metadata.labels.domain}}`}}'
            hubClusterDomain: {{ .Values.clusterDomain | quote }}
            eastDomain: {{ .Values.clusters.east.domain | quote }}
            westDomain: {{ .Values.clusters.west.domain | quote }}
            clusterRole: spoke
            gitops:
              repoUrl: {{ .Values.gitops.repoUrl | quote }}
              revision: {{ .Values.gitops.revision | default "main" | quote }}
      destination:
        name: local-cluster
        namespace: openshift-gitops
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
