{{- range $name, $cluster := .Values.managedClusters }}
{{- if and $cluster.apiUrl $cluster.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-cluster-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
    app.kubernetes.io/part-of: platform-hub-spoke
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  name: {{ $name }}
  server: {{ $cluster.apiUrl }}
  config: |
    {
      "bearerToken": "{{ $cluster.token }}",
      "tlsClientConfig": {
        "insecure": true
      }
    }
{{- end }}
{{- end }}
