apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: Software Templates for Developer Hub
spec:
  targets:
    - ./industrial-edge/template.yaml
    - ./industrial-edge-camel-kaoto/template.yaml
    - ./industrial-edge-delete/template.yaml
    - ./industrial-edge-api-product/template.yaml
    - ./openshift-ai-workspace/template.yaml
    - ./cnv-vm-workshop/template.yaml
