apiVersion: v1
kind: Namespace
metadata:
  name: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  linkAccess: route
