apiVersion: v1
kind: Namespace
metadata:
  name: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  linkAccess: route
---
apiVersion: skupper.io/v2alpha1
kind: AccessGrant
metadata:
  name: spoke-link
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  redemptionsAllowed: 10
  expirationWindow: 720h
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: ie-gateway-east
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: ie-gateway-east
  host: ie-gateway-east
  port: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: ie-gateway-west
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: ie-gateway-west
  host: ie-gateway-west
  port: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: prometheus-east
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: prometheus-east
  host: prometheus-east
  port: 9091
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: prometheus-west
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: prometheus-west
  host: prometheus-west
  port: 9091
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-east-tst
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-east-tst
  host: kafka-east-tst
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-east-stormshift
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-east-stormshift
  host: kafka-east-stormshift
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-west-tst
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-west-tst
  host: kafka-west-tst
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-west-stormshift
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-west-stormshift
  host: kafka-west-stormshift
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: minio-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: minio-hub
  host: minio.industrial-edge-ml-workspace.svc.cluster.local
  port: 9000
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-east-datalake
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-east-datalake
  host: kafka-east-datalake
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-west-datalake
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-west-datalake
  host: kafka-west-datalake
  port: 9092
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: otel-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: otel-hub
  host: otel-hub
  port: 4317
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: otel-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: otel-hub
  host: cluster-collector-collector.openshift-opentelemetry.svc.cluster.local
  port: 4317
