apiVersion: v1
kind: Namespace
metadata:
  name: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: console-metrics-token
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: kafka-console-console-serviceaccount
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-console-monitoring-view
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: kafka-console-console-serviceaccount
  namespace: kafka-console
---
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hostname: kafka-console.{{ .Values.clusterDomain }}
  metricsSources:
    - name: thanos
      type: standalone
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      authentication:
        bearer:
          token:
            valueFrom:
              secretKeyRef:
                name: console-metrics-token
                key: token
      trustStore:
        type: PEM
        content:
          valueFrom:
            configMapKeyRef:
              name: openshift-service-ca.crt
              key: service-ca.crt
    - name: prometheus-east
      type: standalone
      url: http://prometheus-east.service-interconnect.svc.cluster.local:9091
    - name: prometheus-west
      type: standalone
      url: http://prometheus-west.service-interconnect.svc.cluster.local:9091
  kafkaClusters:
    - name: prod-cluster
      metricsSource: thanos
      properties:
        values:
          - name: bootstrap.servers
            value: prod-cluster-kafka-bootstrap.industrial-edge-data-lake.svc.cluster.local:9092
    - name: dev-cluster-east
      metricsSource: prometheus-east
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-east-tst.service-interconnect.svc.cluster.local:9092
    - name: factory-cluster-east
      metricsSource: prometheus-east
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-east-stormshift.service-interconnect.svc.cluster.local:9092
    - name: dev-cluster-west
      metricsSource: prometheus-west
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-west-tst.service-interconnect.svc.cluster.local:9092
    - name: factory-cluster-west
      metricsSource: prometheus-west
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-west-stormshift.service-interconnect.svc.cluster.local:9092
