apiVersion: v1
kind: Namespace
metadata:
  name: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hostname: kafka-console.{{ .Values.clusterDomain }}
  metricsSources:
    - name: thanos
      type: standalone
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      authentication:
        bearer:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      trustStore:
        type: PEM
        content:
          valueFrom:
            configMapKeyRef:
              name: kube-root-ca.crt
              key: ca.crt
  kafkaClusters:
    - name: dev-cluster-east
      metricsSource: thanos
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-east-tst.service-interconnect.svc.cluster.local:9092
    - name: factory-cluster-east
      metricsSource: thanos
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-east-stormshift.service-interconnect.svc.cluster.local:9092
    - name: dev-cluster-west
      metricsSource: thanos
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-west-tst.service-interconnect.svc.cluster.local:9092
    - name: factory-cluster-west
      metricsSource: thanos
      properties:
        values:
          - name: bootstrap.servers
            value: kafka-west-stormshift.service-interconnect.svc.cluster.local:9092
