apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: v1.24.1
  namespace: istio-system
  profile: ambient
  values:
    pilot:
      env:
        PILOT_ENABLE_AMBIENT: "true"
    global:
      platform: openshift
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: sailoperator.io/v1alpha1
kind: IstioCNI
metadata:
  name: default
  namespace: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  version: v1.24.1
  namespace: istio-cni
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- $waypointNamespaces := list
  "industrial-edge-tst-all"
  "industrial-edge-stormshift-messaging"
  "industrial-edge-data-lake"
  "hub-gateway-system"
}}
{{- range $waypointNamespaces }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ . }}-waypoint
  namespace: {{ . }}
  labels:
    istio.io/waypoint-for: service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}
