apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-monitoring-rbac
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: openshift-cluster-observability-operator
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  auth:
    strategy: openshift
  deployment:
    cluster_wide_access: true
    namespace: openshift-cluster-observability-operator
  external_services:
    istio:
      config_map_name: istio-default
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-default
      istiod_deployment_name: istiod-default
    grafana:
      enabled: true
      in_cluster_url: http://grafana-service.openshift-cluster-observability-operator.svc:3000
      url: https://grafana.{{ .Values.clusterDomain }}
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
---
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  name: ossmconsole
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  version: default
  kiali:
    serviceName: kiali
    serviceNamespace: openshift-cluster-observability-operator
