clusterName: ""
clusterDomain: ""
hubClusterDomain: ""
eastDomain: ""
westDomain: ""
clusterRole: spoke

gitops:
  repoUrl: ""
  revision: main

components:
  - id: namespaces
    path: components/namespaces
    namespace: openshift-gitops
  - id: operators
    path: components/operators
    namespace: openshift-operators
  - id: servicemeshoperator3
    path: components/servicemeshoperator3
    namespace: openshift-operators
  - id: industrial-edge-tst
    path: components/industrial-edge-tst
    namespace: industrial-edge-tst-all
  - id: industrial-edge-stormshift
    path: components/industrial-edge-stormshift
    namespace: industrial-edge-stormshift-messaging
  - id: industrial-edge-pipelines
    path: components/industrial-edge-pipelines
    namespace: industrial-edge-ci
  - id: acs-secured-cluster
    path: components/acs-secured-cluster
    namespace: stackrox
  - id: observability
    path: components/observability
    namespace: openshift-cluster-observability-operator
  - id: spoke-dashboards
    path: components/spoke-dashboards
    namespace: openshift-cluster-observability-operator
  - id: istio-monitoring
    path: components/istio-monitoring
    namespace: istio-system
  - id: console-links
    path: components/console-links
    namespace: openshift-gitops
  - id: spoke-gateway
    path: components/spoke-gateway
    namespace: spoke-gateway-system
  - id: spoke-interconnect
    path: components/spoke-interconnect
    namespace: service-interconnect
  - id: rhcl-operator
    path: components/rhcl-operator
    namespace: redhat-connectivity-link-operator
  - id: kiali
    path: components/kiali
    namespace: openshift-cluster-observability-operator
  - id: ie-anomaly-alerter
    path: components/ie-anomaly-alerter
    namespace: industrial-edge-tst-all
  - id: kubecost
    path: components/kubecost
    namespace: kubecost

subscriptions:
  - name: skupper-operator
    namespace: openshift-operators
    channel: stable-2
    source: redhat-operators
  - name: grafana-operator
    namespace: openshift-operators
    channel: v5
    source: community-operators
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: rhacs-operator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-broker-rhel8
    namespace: openshift-operators
    channel: 7.12.x
    source: redhat-operators
