apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: skupper-console
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  host: skupper-console.{{ .Values.clusterDomain }}
  to:
    kind: Service
    name: skupper-network-observer
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
