apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-ods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cluster-observability-operator
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
# COO CSV only supports AllNamespaces (not OwnNamespace/SingleNamespace).
spec: {}
{{- if ne .Values.clusterRole "hub" }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: industrial-edge-tst-all
  namespace: industrial-edge-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - industrial-edge-tst-all
{{- end }}
