apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-ods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
{{- if eq .Values.clusterRole "hub" }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
{{- end }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cluster-observability-operator
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
# COO CSV only supports AllNamespaces (not OwnNamespace/SingleNamespace).
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-tempo-operator
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cnv
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-cnv
{{- if ne .Values.clusterRole "hub" }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: industrial-edge-tst-all
  namespace: industrial-edge-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - industrial-edge-tst-all
{{- end }}
