{{- if .Values.clusters.east.domain }}
apiVersion: v1
kind: Service
metadata:
  name: industrial-edge-east
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ExternalName
  externalName: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.east.domain }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
{{- end }}
---
{{- if .Values.clusters.west.domain }}
apiVersion: v1
kind: Service
metadata:
  name: industrial-edge-west
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ExternalName
  externalName: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.west.domain }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
{{- end }}
