{{- if .Values.clusters.east.domain }}
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: industrial-edge-east
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  hosts:
    - industrial-edge-east.hub-gateway-system.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
  endpoints:
    - address: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.east.domain }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: industrial-edge-east-tls
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: industrial-edge-east.hub-gateway-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.east.domain }}
{{- end }}
---
{{- if .Values.clusters.west.domain }}
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: industrial-edge-west
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  hosts:
    - industrial-edge-west.hub-gateway-system.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
  endpoints:
    - address: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.west.domain }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: industrial-edge-west-tls
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: industrial-edge-west.hub-gateway-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: line-dashboard-industrial-edge-tst-all.{{ .Values.clusters.west.domain }}
{{- end }}
