apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hub-gateway
  namespace: hub-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  host: industrial-edge.{{ .Values.clusterDomain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: hub-gateway-istio
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
