apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-sensor-1
  namespace: ${{ values.namespace }}
  labels:
    app: machine-sensor
    sensor-id: "1"
    app.kubernetes.io/part-of: industrial-edge
    kairos.io/managed: "true"
    kairos.io/environment: ${{ values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-sensor
      sensor-id: "1"
  template:
    metadata:
      labels:
        app: machine-sensor
        sensor-id: "1"
        kairos.io/managed: "true"
        kairos.io/environment: ${{ values.environment }}
    spec:
      containers:
        - name: machine-sensor
          image: quay.io/hybridcloudpatterns/iot-software-sensor:latest
          env:
            - name: MQTT_HOSTNAME
              value: messaging.industrial-edge-tst-all.svc
            - name: MQTT_PORT
              value: "1883"
            - name: SENSOR_DEVICE_ID
              value: "sensor-1"
            - name: SENSOR_GPS
              value: "40.4,-3.7"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-sensor-2
  namespace: ${{ values.namespace }}
  labels:
    app: machine-sensor
    sensor-id: "2"
    app.kubernetes.io/part-of: industrial-edge
    kairos.io/managed: "true"
    kairos.io/environment: ${{ values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-sensor
      sensor-id: "2"
  template:
    metadata:
      labels:
        app: machine-sensor
        sensor-id: "2"
        kairos.io/managed: "true"
        kairos.io/environment: ${{ values.environment }}
    spec:
      containers:
        - name: machine-sensor
          image: quay.io/hybridcloudpatterns/iot-software-sensor:latest
          env:
            - name: MQTT_HOSTNAME
              value: messaging.industrial-edge-tst-all.svc
            - name: MQTT_PORT
              value: "1883"
            - name: SENSOR_DEVICE_ID
              value: "sensor-2"
            - name: SENSOR_GPS
              value: "41.4,-2.2"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
