apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.namespace }}
  labels:
    app.kubernetes.io/part-of: industrial-edge
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "0"
