apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-models
  namespace: industrial-edge-tst-all
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: models
  AWS_S3_ENDPOINT: http://minio-hub.service-interconnect.svc:9000
{{- if .Values.anomalyDetection.enabled }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: anomaly-detection
  namespace: industrial-edge-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: mlserver-1.x
      storage:
        key: aws-connection-models
        path: anomaly-detection/model
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anomaly-detection
  namespace: industrial-edge-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  host: anomaly-detection-industrial-edge-tst-all.{{ include "industrial-edge.domain" . }}
  to:
    kind: Service
    name: anomaly-detection-predictor-default
  port:
    targetPort: http
  tls:
    termination: edge
{{- end }}
