apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-thanos-reader
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-thanos-cluster-monitoring-view
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-thanos-reader
    namespace: openshift-cluster-observability-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-thanos-reader-token
  namespace: openshift-cluster-observability-operator
  annotations:
    kubernetes.io/service-account.name: grafana-thanos-reader
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/service-account-token
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    dashboards: grafana
spec:
  route:
    spec:
      host: grafana.{{ .Values.clusterDomain }}
      port:
        targetPort: grafana
      tls:
        termination: edge
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
      basic: |
        enabled = true
    security:
      admin_user: admin
      admin_password: admin
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: docker.io/grafana/grafana:11.4.0
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: grafana-thanos-reader-token
          key: token
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: "Bearer ${token}"
