apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-hub-catalog-ie-techdocs
  namespace: developer-hub
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  mkdocs.yml: |
{{ .Files.Get "files/techdocs/industrial-edge/mkdocs.yml" | indent 4 }}
  docs/index.md: |
{{ .Files.Get "files/techdocs/industrial-edge/docs/index.md" | indent 4 }}
  docs/data-flow.md: |
{{ .Files.Get "files/techdocs/industrial-edge/docs/data-flow.md" | indent 4 }}
