{{- $clusters := list "east" "west" }}
{{- range $cluster := $clusters }}
---
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: developer-hub
  namespace: {{ $cluster }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  rotation: {}
---
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: developer-hub-read
  namespace: {{ $cluster }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  clusterRole:
    rules:
      - apiGroups: ["metrics.k8s.io"]
        resources:
          - pods
          - nodes
        verbs: [get, list]
      - apiGroups: ["", "apps", "batch", "tekton.dev", "route.openshift.io", "networking.k8s.io", "autoscaling", "gateway.networking.k8s.io", "kafka.strimzi.io", "operators.coreos.com", "packages.operators.coreos.com", "argoproj.io", "networking.istio.io", "security.istio.io", "sailoperator.io"]
        resources:
          - pods
          - pods/log
          - services
          - configmaps
          - limitranges
          - resourcequotas
          - serviceaccounts
          - deployments
          - replicasets
          - statefulsets
          - daemonsets
          - jobs
          - cronjobs
          - events
          - pipelines
          - pipelineruns
          - taskruns
          - routes
          - ingresses
          - networkpolicies
          - horizontalpodautoscalers
          - gateways
          - httproutes
          - grpcroutes
          - referencegrants
          - kafkas
          - kafkatopics
          - kafkausers
          - kafkaconnects
          - subscriptions
          - clusterserviceversions
          - installplans
          - operatorgroups
          - packagemanifests
          - applications
          - virtualservices
          - destinationrules
          - serviceentries
          - authorizationpolicies
          - peerauthentications
          - istios
        verbs: [get, list, watch]
  clusterRoleBinding:
    subject:
      kind: ServiceAccount
      name: developer-hub
      namespace: open-cluster-management-agent-addon
{{- end }}
