{{- $clusters := list "east" "west" }}
{{- range $cluster := $clusters }}
---
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: developer-hub
  namespace: {{ $cluster }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  rotation: {}
---
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: developer-hub-read
  namespace: {{ $cluster }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  clusterRole:
    rules:
      - apiGroups: ["metrics.k8s.io"]
        resources:
          - pods
          - nodes
        verbs: [get, list]
      - apiGroups: ["", "apps", "batch", "tekton.dev", "route.openshift.io", "networking.k8s.io", "autoscaling"]
        resources:
          - pods
          - pods/log
          - services
          - configmaps
          - limitranges
          - resourcequotas
          - serviceaccounts
          - deployments
          - replicasets
          - statefulsets
          - daemonsets
          - jobs
          - cronjobs
          - events
          - pipelines
          - pipelineruns
          - taskruns
          - routes
          - ingresses
          - horizontalpodautoscalers
        verbs: [get, list, watch]
  clusterRoleBinding:
    subject:
      kind: ServiceAccount
      name: developer-hub
      namespace: open-cluster-management-agent-addon
{{- end }}
