clusterDomain: ""
gitops:
  repoUrl: ""
  revision: "main"
clusters:
  east:
    domain: ""
  west:
    domain: ""
managedClusters:
  east:
    apiUrl: ""
    domain: ""
  west:
    apiUrl: ""
    domain: ""
