{{- $ambientNamespaces := list
  "industrial-edge-tst-all"
  "industrial-edge-stormshift-messaging"
  "industrial-edge-ml-workspace"
  "industrial-edge-ci"
  "ml-development"
  "hub-gateway-system"
  "redhat-ods-operator"
  "openshift-cluster-observability-operator"
  "developer-hub"
  "gitea"
  "devspaces"
  "redhat-connectivity-link-operator"
}}
{{- $noMeshNamespaces := list
  "industrial-edge-data-lake"
  "stackrox"
}}
{{- range $ambientNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
{{- range $noMeshNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
